version: '3.7'
services:
  proxy:
    container_name: nginx
    image: "nginx:latest"
    restart: always
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - /home/alpine/nginx/sites-enabled:/etc/nginx/conf.d
      - /home/alpine/nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"