version: '3.7'
services:
  # раскомментировать для локальной установки
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: "postgres"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "P@ssw0rd"
  #   ports:
  #     - "5432:5432"
  web:
    image: bingo:latest
    restart: always
    ports:
      - "30238:30238"